# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "2.6"

install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install coverage"

script:
    - "coverage run --source=dbfkit setup.py test"
